version: '3'

networks:
  beaker:

services:
  beaker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - DEBUG=1
      - LOGLEVEL=INFO
      - PYTHONPATH=/beaker
      - ENABLE_CHECKPOINTS=true
      - TOOL_ENABLED_ASK_USER=true
      - TOOL_ENABLED_RUN_CODE=true
    env_file:
      - .env
    volumes:
      - ./src/beaker_biomedical:/src/beaker_biomedical
      - ./skills:/beaker/.beaker/skills
      - ./skills.json:/beaker/.beaker/skills.json
    networks:
      - beaker
